### ISSUE TITLE
x86版本 运行系统日志报错

### ISSUE THREAD

**Issue by ideatechfr** [kiddin9/OpenWrt_x86-r2s-r4s#272]
装在群晖VMM虚拟机，运行后在系统日志里总有下面的错误提示，请问大佬如何处理？
Sat Jan 23 22:50:26 2021 daemon.err uhttpd[3229]: sh: smartctl: not found
Sat Jan 23 22:50:26 2021 daemon.err uhttpd[3229]: sh: blkid: not found
Sat Jan 23 22:50:26 2021 daemon.err uhttpd[3229]: sh: blkid: not found

**Comment by kunish** [comment]
Same here from a fresh installation.
Wondering if it is a issue with vmware esxi or openwrt it self.
Any idea? It's pretty annoying to me.

**Comment by kunish** [comment]
Alright guys. After a little bit of digging into this issue, I think i finally figured it out. Turns out uhttpd is requiring some dependencies(smartctl and blkid) to show some disk health and identity information.

To fix this, you just simply go into system/software, install the missing packages
- smartmontools
- blkid

After logout and login again you won't see the error messages again now on. That should do the trick.

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/17328586/110993397-31ed8880-83b2-11eb-86e3-83011f3de642.png">
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/17328586/110993425-3dd94a80-83b2-11eb-94a0-14a60d3cfb5b.png">

Hope it helps.

By the way, to the owner of this project, I think it is a amazing piece of work. I really enjoy using it. Keep it up!
